table dataset_fashion_store_channels
	lineageTag: 39ef0706-204a-4210-b14d-9dc1213be952

	column Column1
		dataType: string
		lineageTag: 9df19a50-93d3-4e6c-883f-fd70796805f1
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 03a2bd60-3a03-48dd-b5f0-7a5b39034030
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition dataset_fashion_store_channels = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\danis\Downloads\archive\dataset_fashion_store_channels.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

